name: Publish
on:
  push:
    branches:
      - main
      - beta
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
      - .yarnrc
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
      - .yarnrc
      - LICENSE

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

  setup:
    name: Setup
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    needs:
      - setup
    secrets: inherit

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs:
      - setup
    secrets: inherit

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    needs:
      - lint
      - test
    secrets: inherit
